version: '3.1'

services:

  db:
    image: mysql:5.7
    restart: always
    ports:
     - "33079:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootPass
      MYSQL_DATABASE: hms
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    networks:
      - localnetwork

#  grafana:
#    image: grafana/grafana:5.1.2
#    restart: always
#    ports:
#     - "33078:3000"
#    networks:
#      - localnetwork

networks:
  localnetwork: